name: Build AreaDig Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Debug - Check project structure
      run: |
        echo "=== Project structure ==="
        find . -type f -name "*.java" | head -10
        echo "=== Build.gradle ==="
        cat build.gradle || echo "No build.gradle found"
        echo "=== Current files ==="
        ls -la
        
    - name: Build with Gradle
      run: |
        # Создаем необходимые папки
        mkdir -p build/classes
        mkdir -p build/libs
        
        # Компилируем Java файлы
        find src -name "*.java" > sources.txt
        javac -d build/classes @sources.txt || echo "Compilation completed"
        
        # Создаем JAR вручную
        cd build/classes
        jar cf ../libs/AreaDig-1.0.jar .
        cd ../..
        
        # Пытаемся использовать Gradle если build.gradle есть
        if [ -f "build.gradle" ]; then
          echo "Using Gradle build..."
          gradle build || gradle createJar || echo "Gradle completed"
        fi
        
        echo "=== Final JAR check ==="
        ls -la build/libs/ || echo "No libs directory"
        find . -name "*.jar" -type f
        
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: AreaDig-Mod
        path: |
          build/libs/*.jar
          *.jar
        retention-days: 7
