name: Build AreaDig Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: List build files (debug)
      run: ls -la build/libs/
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: AreaDig-Mod
        path: build/libs/*.jar
        retention-days: 7
